services:
  runner:
    image: scelle/actions-image
    restart: always
    environment:
      - REPO=${GIT_REPO}
      - TOKEN=${GIT_TOKEN}
        # volumes:
          # - /var/run/docker.sock:/var/run/docker.sock  # Монтирование Docker-сокета
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.35'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 128M

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: bgrt
      POSTGRES_USER: shnepsel
      POSTGRES_PASSWORD: 111
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
