name: Deploy PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy PostgreSQL container
        run: |
          docker compose up -d
