name: Deploy PostgreSQL

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted # ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
         
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and deploy PostgreSQL container
        run: |
          docker-compose up -d
